name: Periodic Site Check

on:
  schedule:
    - cron: '0 0,8,10,12,14,16,18,20,22 * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode (shows browser)'
        required: false
        type: boolean
        default: false

jobs:
  check-site:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm run setup
          
      - name: Run check
        env:
          RECORD_VIDEO: true
        run: npm test
        
      - name: Upload video artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-video
          path: test-results/video/*.webm
          retention-days: 7